version: '3'

services:
  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./output:/html
    environment:
      - CADDY_AGREE=true
    restart: always

  postgres:
    image: postgres:latest
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    restart: always

  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config:rw
    restart: always

  meshinfo:
    image: ghcr.io/kevinelliott/meshinfo:0.0.6
    volumes:
      - ./output:/app/output
    environment:
      - ENV_VAR_1=value1
      - ENV_VAR_2=value2
    restart: always
    depends_on:
      - caddy
      - postgres
      - mosquitto
