# trunk-ignore-all(checkov/CKV_DOCKER_3)
FROM node:25.2.1-alpine

LABEL org.opencontainers.image.source="https://github.com/MeshAddicts/meshinfo"
LABEL org.opencontainers.image.description="Realtime web UI to run against a Meshtastic regional or private mesh network."

COPY . .

WORKDIR /frontend

ENV NODE_ENV=dev

RUN npm install -g corepack --force
RUN corepack enable
RUN yarn

EXPOSE 5173
CMD ["/frontend/scripts/run-frontend.sh"]
