services:
  caddy:
    image: caddy:latest
    ports:
      - 8000:80
    volumes:
      - ./caddy/data:/data/caddy
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
      - ./output/static-html:/srv
      - ./spa:/srv/next
      - ./public/images:/srv/images
    environment:
      - CADDY_AGREE=true
    restart: always

  postgres:
    image: postgres:latest
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    restart: always

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/config:/mosquitto/config:rw
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.spa.dev
    ports:
      - 5173:5173
    environment:
      - VITE_API_BASE_URL=http://localhost:9000
      - NODE_ENV=dev
    restart: always

  meshinfo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.json:/app/config.json
      - ./output:/app/output
      - ./templates:/app/templates
      - ./spa:/app/spa
    ports:
      - 9000:9000
    environment:
      - PYTHONUNBUFFERED=1
      - ALLOW_ORIGINS=*
    restart: always
    depends_on:
      - caddy
      - postgres
      - mqtt
