services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: meshinfo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - meshinfo_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d meshinfo"]
      interval: 5s
      timeout: 5s
      retries: 20

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/config:/mosquitto/config:rw
    restart: unless-stopped

  meshinfo:
    image: ghcr.io/meshaddicts/meshinfo:latest
    volumes:
      - ./config.toml:/app/config.toml
      - ./output:/app/output
      - ./postgres:/app/postgres:ro
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 9000:9000
    restart: unless-stopped
    depends_on:
      - postgres
      - mqtt

  frontend:
    image: ghcr.io/meshaddicts/meshinfo-spa:latest
    ports:
      - 8000:80
    env_file:
      - path: ./frontend/.env
        required: false

    environment:
      NODE_ENV: production
    restart: unless-stopped

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/data:/data/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./output/static-html:/srv
      - ./public/images:/srv/images
    environment:
      - CADDY_AGREE=true
    restart: unless-stopped
    depends_on:
      - meshinfo
      - frontend

volumes:
  meshinfo_pgdata: