name: Continuous Integration Build

on:
  pull_request:
    branches:
      - "main"
      - "develop"
  workflow_dispatch:

jobs:
  build-main:
    name: Build Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.1"
      - name: Enable yarn
        run: corepack enable
      - name: Install dependencies
        run: yarn
        working-directory: ./frontend
      - name: Run build
        run: yarn build
        working-directory: ./frontend
  build-spa:
    name: Build Dockerfile.spa
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.1"
      - name: Enable yarn
        run: corepack enable
      - name: Install dependencies
        run: yarn
        working-directory: ./frontend
      - name: Run build
        run: yarn build
        working-directory: ./frontend
